name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt install -y nasm binutils

    - name: Build
      run: make build

    - name: Test
      run: make test
